### ISSUE TITLE
malloc / free making unsupported syscalls

### ISSUE THREAD

**Issue by ElvishJerricco** [WebGHC/musl#5]
Turns out our "working" malloc actually only works when Clang optimizes it to `simple_malloc`. `malloc` and probably `free` both depend on some other syscalls.

@mvogelsang @mulderr, you've both run into this. Can you guys discuss your findings?

**Comment by mulderr** [comment]
Good (confirmed to be `__simple_malloc`):
```c
int main() {
  char *s = malloc(64);
  memset(s, 0x41, 63);
  s[63] = '\0';
  printf("%s\n", s);
  return 0;
}
```

Adding `free` makes it bad:
```c
int main() {
  char *s = malloc(64);
  memset(s, 0x41, 63);
  s[63] = '\0';
  printf("%s\n", s);
  free(s);
  return 0;
}
```

Good trace:
```
SYS_brk 0 undefined undefined undefined undefined undefined
wasm.js:2223 SYS_brk 196608 undefined undefined undefined undefined undefined
wasm.js:2223 SYS_ioctl 1 21523 62456 undefined undefined undefined
wasm.js:407 warning: ioctl being ignored
wasm.js:2223 SYS_writev 1 62432 2 undefined undefined undefined
wasm.js:39 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
wasm.js:2265 0
```

Bad trace:
```
SYS_brk 0 undefined undefined undefined undefined undefined
wasm.js:2223 SYS_brk 196608 undefined undefined undefined undefined undefined
wasm.js:2223 SYS_rt_sigprocmask 0 1132 71712 8 undefined undefined
wasm.js:2223 SYS_gettid undefined undefined undefined undefined undefined undefined
wasm.js:2223 SYS_tkill 1 6 undefined undefined undefined undefined
wasm.js:2267 SYS_tkill NYI
```
I have "best effort" implementations for `rt_sigprocmask` and `gettid` which may be causing problems but anyway what @ElvishJerricco said - adding a `free` in this case makes clang use regular `malloc` instead of `__simple_malloc`.

Towards the end `malloc` calls `trim`. `Trim` in turn calls `free` (unless a certain condition is true) and from there we get an `abort`. So the problem is really in `free`.

To be more precise [here](https://github.com/WebGHC/musl/blob/syscalls-js/src/malloc/malloc.c#L497) because of [this](https://github.com/WebGHC/musl/blob/syscalls-js/src/internal/atomic.h#L127) call and [this](https://github.com/WebGHC/musl/blob/syscalls-js/arch/wasm32/atomic_arch.h#L9) definition.

Does anyone know what `a_cas` is supposed to do? Should we be implementing it or not? In other words can we rule out that this particular definition was just put in there to stitch things together?

Probably this: https://en.wikipedia.org/wiki/Compare-and-swap

**Comment by mulderr** [comment]
I am completely unsure what is the correct course of action here but, as an interesting observation, if I do this (basically copied from wikipedia):
```c
#define a_cas a_cas
static inline int a_cas(volatile int *p, int t, int s)
{
  int old = *p;
  if (old == t)
    *p = s;
  return old;
}
```
then the above bad version starts working.

Edit: and with that change the trace from the previously bad program now exactly matches the good and I can confirm it is using `malloc` instead of `__simple_malloc`. To sum up I don't think we're missing any syscalls. It's just possibly the missing definition of `a_cas`. @mvogelsang would this agree with what you're seeing?

**Comment by ElvishJerricco** [comment]
@mulderr Huh. That's from that atomics.h file, right? Aren't there a number of thing stubbed our with abort in there? I think we can give them non-atomic implementations like that one since we don't have thread yet. Once we have threads, and clang has inline asm for wasm, we can go back and give them proper implementations. If that fixes this issue, I say we go for it

**Comment by mulderr** [comment]
Yeah, exactly [here](https://github.com/WebGHC/musl/blob/syscalls-js/arch/wasm32/atomic_arch.h#L9).

It sure looks good enough at first glance. Also, I've looked through other architectures and none just `abort` so that leads me to think someone left this to be implemented a later time. I may be wrong though. WASM is pretty unique.

**Comment by ElvishJerricco** [comment]
Cool. @mulderr if you want to send a PR, I'll merge it :)

**Comment by mulderr** [comment]
I put that together with other stuff into existing PR. Hope that's ok.
